name: Cypress Tests (Cloud)

on:
  pull_request:
    branches:
      - main
    paths-ignore:
          - 'README.md' 
  push:
    branches:
      - staging
    paths-ignore:
          - 'README.md' 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (Cypress Cloud)
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: false
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_BASE_URL: https://www.certiqa-qazando.com/